set DEVTRK=trunk
set DEVBRA=%DEVTRK%
set BLDTGT=192.168.56.102
set SDKVER=RECOIL_SDK
set SCSREV=00000
set BLDUSR=recoil
set BLDPWD=recoil
set DSTPTH=E:\
set PRJDRV=Y
set PRJDIR="Projects"
set SUBDIR="openwrt"
set SVNDRV=C
set SVNDIR="\Source"
set MAKCMD="make -j1 V=s"
set CLNCMD="make clean"
set CFGDIR="include\config"
set PRDCOD=RECOIL_
set PRDDIR="recoil"
set BLDTYP=FW
set BRDCOD=BS
